#!/bin/sh

set -o errexit
set -o nounset


celery flower \
    --app=django_sample_project.celery_app \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
